---
Name: twilioauthenticatorconfig
---
# Register the method
SilverStripe\MFA\Service\MethodRegistry:
  methods:
    otp: XD\OTPAuthenticator\Method

# Register the default provider
SilverStripe\Core\Injector\Injector:
  XD\OTPAuthenticator\Providers\SendProvider:
    class: XD\OTPAuthenticator\Providers\EmailProvider

SilverStripe\Security\Member:
  extensions:
    - XD\OTPAuthenticator\Extensions\MemberExtension

SilverStripe\MFA\Authenticator\LoginHandler:
  extensions:
    - XD\OTPAuthenticator\Extensions\LoginHandlerExtension